# Generated by Django 2.2 on 2020-04-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={'ordering': ['name']},
        ),
    ]
