# Generated by Django 2.2 on 2020-05-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0002_auto_20200427_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={},
        ),
    ]
