# Generated by Django 2.2 on 2020-05-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0003_auto_20200504_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={'ordering': ['name']},
        ),
    ]
