# Generated by Django 2.2 on 2020-04-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitOverseer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KingdomHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('road', models.CharField(max_length=300)),
                ('postcode', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('wifi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.KingdomHall')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.Circuit')),
                ('circuit_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.CircuitSection')),
            ],
        ),
    ]
