# Generated by Django 2.2 on 2020-04-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='circuit_section',
        ),
    ]
