# Generated by Django 2.2 on 2020-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_auto_20200430_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitoverseer',
            old_name='number',
            new_name='email',
        ),
        migrations.AddField(
            model_name='circuitoverseer',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
