# Generated by Django 2.2 on 2020-04-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.DateField()),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.Congregation')),
                ('visiting_co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.CircuitOverseer')),
            ],
            options={
                'ordering': ['monday'],
            },
        ),
    ]
