# Generated by Django 2.2 on 2020-04-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.Congregation'),
        ),
    ]
