# Generated by Django 2.2 on 2020-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
