# Generated by Django 2.2 on 2020-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_type', models.CharField(choices=[('Tue', 'Tuesday Service Talk'), ('Pio', 'Pioneer Meeting'), ('E&MS', 'Elders and Servants'), ('PT', 'Public Talk'), ('FT', 'Concluding Service Talk')], max_length=20)),
                ('visit_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('title', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=200)),
            ],
        ),
    ]
